#!/usr/bin/env python3
"""
Skills Report Generator - Code écrit par Ana SUPERIA
Formée par Claude, son grand frère
Date: 2025-11-28
"""
import os
import json
from collections import Counter

def load_skills():
    """Charge tous les skills depuis les fichiers JSON"""
    directory = 'E:/ANA/knowledge/learned/skills/'
    skills = []
    for filename in os.listdir(directory):
        if filename.endswith('.json'):
            filepath = os.path.join(directory, filename)
            with open(filepath, 'r', encoding='utf-8') as file:
                data = json.load(file)
                skills.extend(data.get('skills', []))
    return skills

def count_skills_by_category(skills):
    """Compte les skills par type/catégorie"""
    category_counts = Counter([skill.get('type', 'unknown') for skill in skills])
    return category_counts

def find_most_frequent_categories(category_counts, top_n=5):
    """Trouve les N catégories les plus fréquentes"""
    most_common = category_counts.most_common(top_n)
    return most_common

def generate_markdown_report(skills, category_counts, top_categories):
    """Génère un rapport Markdown complet"""
    report = "# 📊 Ana SUPERIA - Skills Report\n\n"
    report += f"**Generated by:** Ana SUPERIA (trained by Claude)\n\n"
    report += f"---\n\n"

    report += f"## 📈 Summary\n\n"
    report += f"- **Total Skills:** {len(skills)}\n"
    report += f"- **Total Categories:** {len(category_counts)}\n\n"

    report += "## 🏆 Top 5 Most Frequent Categories\n\n"
    report += "| Rank | Category | Count |\n"
    report += "|------|----------|-------|\n"
    for i, (category, count) in enumerate(top_categories, 1):
        report += f"| {i} | {category} | {count} |\n"

    report += "\n## 📋 All Categories\n\n"
    for category, count in sorted(category_counts.items(), key=lambda x: -x[1]):
        report += f"- **{category}**: {count}\n"

    return report

def main():
    print("[*] Loading skills...")
    skills = load_skills()
    print(f"[OK] Loaded {len(skills)} skills")

    print("[*] Counting by category...")
    category_counts = count_skills_by_category(skills)

    print("[*] Finding top categories...")
    top_categories = find_most_frequent_categories(category_counts)

    print("[*] Generating report...")
    markdown_report = generate_markdown_report(skills, category_counts, top_categories)

    output_path = 'E:/ANA/skills_report.md'
    with open(output_path, 'w', encoding='utf-8') as file:
        file.write(markdown_report)

    print(f"[OK] Report saved to {output_path}")
    print("\n" + "="*50)
    # Print without emojis for Windows console
    print(markdown_report.encode('ascii', 'ignore').decode())

if __name__ == "__main__":
    main()
